### ISSUE TITLE
What is the purpose of this if statement in getch?

### ISSUE THREAD

**Issue by dospunk** [adam-mcdaniel/oakc#13]
```c
if (ch == '\r') {
    ch = getchar();
}
```
I assume it's to deal with enter inserting `\r\n` instead of just `\n`, but I want to make sure that's correct

**Comment by adam-mcdaniel** [comment]
It's meant to prevent `getch` from ever returning a `'\r'` character. I mostly did this for compatibility between *nix and windows.

**Comment by dospunk** [comment]
Got it, thanks!
