### ISSUE TITLE
compile time flags are constrained to the global scope

### ISSUE THREAD

**Issue by kevinramharak** [adam-mcdaniel/oakc#26]
So 'hardware' limitations force me to write the following code:
```rust
	fn run(self: &Machine) {
		let len = strlen(self->code);
		#[if (TARGET == 'm') {
			let counter = 0;
		}]
		while self->ins_ptr != len) {
			#[if (TARGET == 'm') {
                                counter = counter + 1;
				if counter > 50 {
					counter = 0;
					_sleep!();
				}
			}]
			if self->token == '+' { self.plus() }
			if self->token == '-' { self.minus() }
			if self->token == '<' { self.left() }
			if self->token == '>' { self.right() }
			if self->token == ',' { self.in() }
			if self->token == '.' { self.out() }
			if self->token == '[' { self.loop() }
			if self->token == ']' { self.end() }
			else {
				self->ins_ptr = self->ins_ptr + 1;
			}
		}
	}
```
But it fails:
```
$ cargo run -- --mar ./examples/flags/if.ok
   Compiling oakc v0.3.0 (C:\Users\Kevin\Projects\oakc)                                                                                                                                          
    Finished dev [unoptimized + debuginfo] target(s) in 2.05s
     Running `target\debug\oak.exe --mar ./examples/flags/if.ok`
  |
8 | #[if(THROW_ERROR) {
  | ^
  |
  = unexpected `#`
error: process didn't exit successfully: `target\debug\oak.exe --mar ./examples/flags/if.ok` (exit code: 1)
```
Is this intended?

**Comment by kevinramharak** [comment]
That makes sense. Is it okay for them to be statements or does that have unwanted side effects?

**Comment by adam-mcdaniel** [comment]
I don't think so, but I could be wrong. I'm not sure I want to allow conditional compilation in a non-global scope. I think that it's better for them to remain in the global scope, but I'm not convinced of either way yet. I think it promotes hacking together clauses of a function based on the condition as opposed to writing entire implementations optimized for each condition. What do you think?

**Comment by kevinramharak** [comment]
Yeah, that is a valid concern. You only want the good parts of the C preprocessor 👍 I think the duplicate code is worth forcing the programmer to be more clear with the intention of the code. Reading code is a lot harder than writing it.
