### ISSUE TITLE
Compiler will only use the C target

### ISSUE THREAD

**Issue by dospunk** [adam-mcdaniel/oakc#48]
This can be seen by adding `println!("Using C target");` to the top of the `compile` function in `src/target/c.rs`, rebuilding, and then running `./target/debug/oak -g c <any Oak file>`.

**Comment by kevinramharak** [comment]
Seems to work fine on my repo. Are you sure you merged in the latest changes from upstream? I also suggest using `cargo run -- -g ./examples/hello_world.ok`. It will build the binary if there are any changes and then pass everything after `--`  to the oak binary.

**Comment by adam-mcdaniel** [comment]
I'm able to reproduce this and I've found the source of the error. In `bin.rs`, the argument parser matches the `-c` flag (to use the C backend) against the `c` compiler switch (to compile the file) for some reason. I'm issuing a fix for this.

**Comment by adam-mcdaniel** [comment]
Im fixing this by changing the `-c` backend flag to the `-cc` backend flag.

**Comment by adam-mcdaniel** [comment]
I'm sorry it took so long to merge, but PR #54 fixed this issue.
